#include "movable.hpp"
#include "Pacman/pacman.hpp"
#include "Ghost/ghost.hpp"
#include "Ghost/Blinky/blinky.hpp"
#include "Ghost/Pinky/pinky.hpp"
#include "Ghost/Inky/inky.hpp"
#include "Ghost/Clyde/clyde.hpp"